# specify target system name (mandatory)
SET(CMAKE_SYSTEM_NAME Linux)

SET(CMAKE_SYSTEM_PROCESSOR arm)
SET(CMAKE_SYSTEM_VERSION 1)
SET(CMAKE_CROSSCOMPILING 1)

# specify the cross compiler
SET(CMAKE_C_COMPILER arm-linux-gnueabi-gcc)
SET(CMAKE_CXX_COMPILER arm-linux-gnueabi-g++)

# specify the search directories for FIND_XXX() command 
SET(CMAKE_FIND_ROOT_PATH  /usr/arm-linux-gnueabi)

# find programs for FIND_PROGRAM() command (NEVER, ONLY or BOTH)
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)

# find libraries and headers for FIND_LIBRARY() command and FIND_PATH()/FIND_FILE() command
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE NEVER)

# specify library path
SET(CMAKE_LIBRARY_PATH ${CMAKE_LIBRARY_PATH} /home/yuhao/ncurses-5.9_build/lib)

# specify install dir
SET(CMAKE_INSTALL_PREFIX /home/yuhao/mysql-5.7.17_arm_build)

# MySQL specific settings
SET(BOOST_INCLUDE_DIR /home/yuhao/mysql-5.7.17_arm/boost/boost_1_59_0)

SET(STACK_DIRECTION 1)

SET(DEFAULT_CHARSET utf8)
SET(DEFAULT_COLLATION utf8_general_ci)

SET(WITH_UNIT_TESTS OFF)
SET(WITH_EMBEDDED_SERVER TRUE)

SET(WITH_EXAMPLE_STORAGE_ENGINE OFF)
SET(WITH_FEDERATED_STORAGE_ENGINE OFF)
SET(WITH_PARTITION_STORAGE_ENGINE OFF)
SET(WITH_DEBUG OFF)

# not execute CMake TRY_RUN() for cross compile
SET(HAVE_C_SHIFT_OR_OPTIMIZATION_BUG FAILED_TO_RUN)
SET(HAVE_CXX_SHIFT_OR_OPTIMIZATION_BUG_EXITCODE FAILED_TO_RUN)
SET(HAVE_C_FLOATING_POINT_FUSED_MADD_EXITCODE FAILED_TO_RUN)
SET(HAVE_CXX_FLOATING_POINT_FUSED_MADD_EXITCODE FAILED_TO_RUN)
SET(HAVE_LLVM_LIBCPP_EXITCODE FAILED_TO_RUN)
SET(HAVE_FALLOC_PUNCH_HOLE_AND_KEEP_SIZE_EXITCODE FAILED_TO_RUN)

